### ISSUE TITLE
Missing 2.1.1 in composer

### ISSUE THREAD

**Issue by denissdubinin** [bragento/magento2-cash-on-delivery-fee#21]
Version 2.1.1 is not available in composer. Latest available version is 2.1.0.

There is a known issue with github hooks: pushing a tag pointing to a commit which is already available on Github (and so not pushing any new commit) does not trigger the push webhook, and so Packagist is not notified.
The workaround is to trigger a manual update in the packagist UI. Otherwise the tag will be picked only the next time you push a commit to github.

Screenshot - http://prntscr.com/na33vv
Please check it out https://packagist.org/packages/brandung/cash-on-delivery-fee

**Comment by davidverholen** [comment]
@denissdubinin thanks for the hint, just updated the package
