### ISSUE TITLE
PHP version Requirements problem

### ISSUE THREAD

**Issue by miguelcobain** [bragento/magento2-cash-on-delivery-fee#3]
I got the following problem while trying to install this great extension:

![php](https://user-images.githubusercontent.com/631691/27081135-f6cf83dc-5036-11e7-864b-090ed14e5111.png)

Seems strange because I'm using PHP 7, like proven in the screenshot.
Is this related with the package?

**Comment by davidverholen** [comment]
Hi @miguelcobain, this module contains some php 5 incompatible parts and can only be run on php7.
It seems that you have php 5.6 installed so composer refuses to install the module

**Comment by miguelcobain** [comment]
@davidverholen as you can see from the screenshot, i ran `php -v` and it tells me I have PHP 7.0.19

Very strange. :/

**Comment by davidverholen** [comment]
the composer maybe runs with an own php version on your server.
you can disable the env checking of composer by adding the switch --ignore-platform-reqs.

I think it's:

composer require --ignore-platform-reqs brandung/cash-on-delivery-fee:^1.0

**Comment by miguelcobain** [comment]
@davidverholen thank you very much for the hint. That was indeed the problem. 💯
