### ISSUE TITLE
error on install

### ISSUE THREAD

**Issue by calamusid** [bragento/magento2-cash-on-delivery-fee#5]
I tired:
composer require msp/cashondelivery
Using version ^1.1 for msp/cashondelivery
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Package fabpot/php-cs-fixer is abandoned, you should avoid using it. Use friendsofphp/php-cs-fixer instead.
Generating autoload files

and also

composer require brandung/cash-on-delivery-fee:^1.0
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing brandung/cash-on-delivery-fee (1.0.0): Downloading (100%)         
Package fabpot/php-cs-fixer is abandoned, you should avoid using it. Use friendsofphp/php-cs-fixer instead.
Writing lock file
Generating autoload files

how can I fix it?

thanks
Piero

**Comment by davidverholen** [comment]
it's not an error, it's a warning, that the package fabpot/php-cs-fixer is abandoned and should not be used anymore. 

It is a dependency of magento itself so you have to wait until they update it (which also has happened in the develop branch)
