### ISSUE TITLE
M2.2 compatibility

### ISSUE THREAD

**Issue by epicglows** [bragento/magento2-cash-on-delivery-fee#6]
Hi,

Do you intend to update for M2.2?

-------------------------

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - brandung/cash-on-delivery-fee 1.0.0 requires magento/module-quote ^100.1.4 -> satisfiable by magento/module-quote[100.1.5, 100.1.4, 100.2.0-rc20].
    - brandung/cash-on-delivery-fee 1.0.0 requires magento/module-quote ^100.1.4 -> satisfiable by magento/module-quote[100.1.5, 100.1.4, 100.2.0-rc20].
    - Can only install one of: magento/module-quote[101.0.0, 100.1.5].
    - Can only install one of: magento/module-quote[101.0.0, 100.1.4].
    - Can only install one of: magento/module-quote[101.0.0, 100.1.5].
    - Can only install one of: magento/module-quote[101.0.0, 100.2.0-rc20].
    - magento/product-community-edition 2.2.0 requires magento/module-quote 101.0.0 -> satisfiable by magento/module-quote[101.0.0].
    - Installation request for magento/product-community-edition 2.2 -> satisfiable by magento/product-community-edition[2.2.0].
    - Installation request for brandung/cash-on-delivery-fee ^1.0 -> satisfiable by brandung/cash-on-delivery-fee[1.0.0].

-------------------------

**Comment by davidverholen** [comment]
we do not really use this module since it was primarily developed for a training.
I'll just losen up the dependencies so it should be installable with 2.2 again. Let us know if you encounter any problems
